# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalProject.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1432, 878)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 200, 1331, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_Dragging = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Dragging.setEnabled(True)
        self.checkBox_Dragging.setGeometry(QtCore.QRect(170, 480, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Dragging.setFont(font)
        self.checkBox_Dragging.setChecked(False)
        self.checkBox_Dragging.setObjectName("checkBox_Dragging")
        self.horizontalSlider_zoom = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_zoom.setGeometry(QtCore.QRect(340, 480, 181, 22))
        self.horizontalSlider_zoom.setMaximum(200)
        self.horizontalSlider_zoom.setProperty("value", 150)
        self.horizontalSlider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_zoom.setObjectName("horizontalSlider_zoom")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(290, 480, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_Exit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Exit.setGeometry(QtCore.QRect(810, 560, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox_3)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 20, 941, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setMouseTracking(False)
        self.openGLWidget.setObjectName("openGLWidget")
        self.MouseLocation = QtWidgets.QLineEdit(self.groupBox_3)
        self.MouseLocation.setGeometry(QtCore.QRect(20, 480, 121, 22))
        self.MouseLocation.setText("")
        self.MouseLocation.setAlignment(QtCore.Qt.AlignCenter)
        self.MouseLocation.setObjectName("MouseLocation")
        self.pushButton_SwapLinks = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SwapLinks.setGeometry(QtCore.QRect(560, 480, 93, 28))
        self.pushButton_SwapLinks.setObjectName("pushButton_SwapLinks")
        self.checkBox_ShowConstruction = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_ShowConstruction.setEnabled(True)
        self.checkBox_ShowConstruction.setGeometry(QtCore.QRect(730, 480, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_ShowConstruction.setFont(font)
        self.checkBox_ShowConstruction.setChecked(False)
        self.checkBox_ShowConstruction.setObjectName("checkBox_ShowConstruction")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(300, 550, 351, 80))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Start.setGeometry(QtCore.QRect(0, 30, 93, 28))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Stop.setGeometry(QtCore.QRect(250, 30, 93, 28))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_PauseResume = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_PauseResume.setGeometry(QtCore.QRect(100, 30, 141, 28))
        self.pushButton_PauseResume.setObjectName("pushButton_PauseResume")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(980, 20, 281, 371))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(20, 30, 111, 16))
        self.label.setObjectName("label")
        self.label_a0 = QtWidgets.QLabel(self.groupBox_4)
        self.label_a0.setGeometry(QtCore.QRect(50, 60, 55, 16))
        self.label_a0.setObjectName("label_a0")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(24, 120, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(24, 150, 121, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(50, 270, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(50, 310, 55, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_a0 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_a0.setGeometry(QtCore.QRect(140, 60, 113, 22))
        self.lineEdit_a0.setObjectName("lineEdit_a0")
        self.lineEdit_a = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_a.setGeometry(QtCore.QRect(140, 90, 113, 22))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.lineEdit_StartAngle = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_StartAngle.setGeometry(QtCore.QRect(140, 120, 113, 22))
        self.lineEdit_StartAngle.setObjectName("lineEdit_StartAngle")
        self.lineEdit_EndAngle = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_EndAngle.setGeometry(QtCore.QRect(140, 150, 113, 22))
        self.lineEdit_EndAngle.setObjectName("lineEdit_EndAngle")
        self.lineEdit_b0 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_b0.setGeometry(QtCore.QRect(140, 270, 113, 22))
        self.lineEdit_b0.setObjectName("lineEdit_b0")
        self.lineEdit_b = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_b.setGeometry(QtCore.QRect(140, 310, 113, 22))
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 1331, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_Select = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Select.setGeometry(QtCore.QRect(52, 27, 311, 31))
        self.pushButton_Select.setObjectName("pushButton_Select")
        self.filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.filename.setGeometry(QtCore.QRect(410, 21, 851, 51))
        self.filename.setText("")
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setObjectName("filename")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenGL"))
        self.groupBox_3.setTitle(_translate("Dialog", "Animation Drawing"))
        self.checkBox_Dragging.setText(_translate("Dialog", "Dragging"))
        self.label_20.setText(_translate("Dialog", "Zoom"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_SwapLinks.setText(_translate("Dialog", "Swap Links"))
        self.checkBox_ShowConstruction.setText(_translate("Dialog", "Show Construction"))
        self.groupBox.setTitle(_translate("Dialog", "Anamation Controls"))
        self.pushButton_Start.setText(_translate("Dialog", "Start"))
        self.pushButton_Stop.setText(_translate("Dialog", "Stop"))
        self.pushButton_PauseResume.setText(_translate("Dialog", "Pause/Resume"))
        self.groupBox_4.setTitle(_translate("Dialog", "Design Summary"))
        self.label.setText(_translate("Dialog", "Driven Link:"))
        self.label_a0.setText(_translate("Dialog", "a0:"))
        self.label_3.setText(_translate("Dialog", "a:"))
        self.label_4.setText(_translate("Dialog", "Starting Angle:"))
        self.label_5.setText(_translate("Dialog", "Ending Angle:"))
        self.label_6.setText(_translate("Dialog", "Follower Link"))
        self.label_7.setText(_translate("Dialog", "b0:"))
        self.label_8.setText(_translate("Dialog", "b:"))
        self.groupBox_2.setTitle(_translate("Dialog", "File Select"))
        self.pushButton_Select.setText(_translate("Dialog", "Select and Read Fourbar Design File"))

